name: check_gold_price
on:
  schedule:
    - cron: "30 1 * * *"  # Runs at 1:30 AM IST (8 PM UTC)
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape_gold_price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Gold Price Scraper
        env:
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}  # Uses GitHub Secret
        run: python gold_price_scraper.py
